### ISSUE TITLE
Buildpack failing due to access restriction on tar.gz file

### ISSUE THREAD

**Issue by jonnor** [piotras/heroku-buildpack-gettext#1]
We're getting the following failures trying to deploy an Heroku app using this buildpack

```
remote: =====> Downloading Buildpack: https://github.com/piotras/heroku-buildpack-gettext
remote: =====> Detected Framework: Gettext library
remote: -----> Installing gettext...
remote: 
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Exiting with failure status due to previous errors
remote: 
remote:  !     Push rejected, failed to compile Multipack app
```

This looks to be because `https://s3-eu-west-1.amazonaws.com/midgard-heroku/gettext.tar.gz` gives

```
<Error><Code>AllAccessDisabled</Code><Message>All access to this object has been disabled</Message><RequestId>E31CCE48B62CAA05</RequestId><HostId>B4g1o/69P3Efb58iqkirXk73BAJtC7y48gZztb6NuoV3F9ZeX4Al9dkU6J8SmUMTnAFBnog+YYU=</HostId></Error>
```

We're using this in production so this is blocking our deploys.
Can you fix, or upload the tarball to another location so we can refer to it in another buildpack?

**Comment by piotras** [comment]
Sorry, I do not think it's possible atm :( I think I switched to batch builds at some point: https://github.com/piotras/MDTs/blob/master/build-heroku-packs.sh.

**Comment by jonnor** [comment]
Not even upload of the original file? :(
