### ISSUE TITLE
Using Django manage.py compilemessages

### ISSUE THREAD

**Issue by addodelgrossi** [piotras/heroku-buildpack-gettext#5]
Hi, 

This is a question,  not a bug .

I installed Buildpacks, but I have a question, how to use the command compilemessages after install Buildpacks .

Thanks
Addo

**Comment by zuck** [comment]
Add a `bin/post_compile` file in the root of your app with the following content:

```
set -eo pipefail

# The post_compile hook is run by heroku-buildpack-python
indent() {
   RE="s/^/       /"
   [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
}

echo "-----> In post-compile hook"

export PATH=/app/gettext/bin:$PATH
MANAGE_FILE=$(find . -maxdepth 3 -type f -name 'manage.py' | head -1)
MANAGE_FILE=${MANAGE_FILE:2}

echo "-----> Compiling translation files"

# Workaround to compile only dictionaries of this project, skipping deps.
python "$MANAGE_FILE" compilemessages 2>&1 | indent

echo "-----> Done post-compile hook"
echo ""
```

And remember to add this buildpack before the `heroku/python` one.

`heroku buildpacks:set -i 1 https://github.com/piotras/heroku-buildpack-gettext.git`

Then, please wait for the merging of #7, or use my fork until that:

`heroku buildpacks:set -i 1 https://github.com/zuck/heroku-buildpack-gettext.git#fix-missing-path`

**Comment by Unviray** [comment]
Why I have deployment failed with manage.py error
```
File "manage.py", line 16
    ) from exc 
         ^
SyntaxError: invalid syntax
```
